//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS
    {
        public CLASS()
        {
            this.STUDENTINCLASS = new HashSet<STUDENTINCLASS>();
        }
    
        public string IDCLASS { get; set; }
        public Nullable<decimal> GRADELEVELID { get; set; }
        public string NAME { get; set; }
    
        public virtual GRADELEVEL GRADELEVEL { get; set; }
        public virtual ICollection<STUDENTINCLASS> STUDENTINCLASS { get; set; }
    }
}
