//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEARNINGOUTCOMES
    {
        public string LEARNINGOUTCOMESID { get; set; }
        public string TYPERESULTID { get; set; }
        public string MSHOCSINH { get; set; }
        public string SCHOOLYEARID { get; set; }
        public Nullable<decimal> MEDIUMSCORE { get; set; }
        public string CONDUCT { get; set; }
        public string GRADE { get; set; }
    
        public virtual SCHOOLYEAR SCHOOLYEAR { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        public virtual TYPERESULT TYPERESULT { get; set; }
    }
}
