//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyHocSinhEntities : DbContext
    {
        public QuanLyHocSinhEntities()
            : base("name=QuanLyHocSinhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACCOUNT> ACCOUNTS { get; set; }
        public DbSet<CLASS> CLASS { get; set; }
        public DbSet<GRADELEVEL> GRADELEVELS { get; set; }
        public DbSet<LEARNINGOUTCOMES> LEARNINGOUTCOMES { get; set; }
        public DbSet<SCHOOLYEAR> SCHOOLYEARS { get; set; }
        public DbSet<SEMESTER> SEMESTERS { get; set; }
        public DbSet<STUDENT> STUDENTS { get; set; }
        public DbSet<STUDENTINCLASS> STUDENTINCLASS { get; set; }
        public DbSet<SUBJECT> SUBJECTS { get; set; }
        public DbSet<TYPEACCOUNT> TYPEACCOUNTS { get; set; }
        public DbSet<TYPERESULT> TYPERESULTS { get; set; }
        public DbSet<TESTSCORES> TESTSCORES { get; set; }
    }
}
