//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEMESTER
    {
        public SEMESTER()
        {
            this.TESTSCORES = new HashSet<TESTSCORES>();
        }
    
        public decimal SEMESTERID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> COEFFICIENT { get; set; }
    
        public virtual ICollection<TESTSCORES> TESTSCORES { get; set; }
    }
}
