//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public STUDENT()
        {
            this.LEARNINGOUTCOMES = new HashSet<LEARNINGOUTCOMES>();
            this.STUDENTINCLASS = new HashSet<STUDENTINCLASS>();
            this.TESTSCORES = new HashSet<TESTSCORES>();
            this.ACCOUNT = new HashSet<ACCOUNT>();
        }
    
        public string MSHOCSINH { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public Nullable<decimal> SEX { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
    
        public virtual ICollection<LEARNINGOUTCOMES> LEARNINGOUTCOMES { get; set; }
        public virtual ICollection<STUDENTINCLASS> STUDENTINCLASS { get; set; }
        public virtual ICollection<TESTSCORES> TESTSCORES { get; set; }
        public virtual ICollection<ACCOUNT> ACCOUNT { get; set; }
    }
}
