//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTSCORES
    {
        public string SUBJECTID { get; set; }
        public decimal SEMESTERID { get; set; }
        public string SCHOOLYEARID { get; set; }
        public string MSHOCSINH { get; set; }
        public Nullable<decimal> SCORE_5M { get; set; }
        public Nullable<decimal> SCORE_15M { get; set; }
        public Nullable<decimal> SCORE_45M { get; set; }
        public Nullable<decimal> SCORE_MIDYEAR { get; set; }
        public Nullable<decimal> SCORE_ENDYEAR { get; set; }
    
        public virtual SCHOOLYEAR SCHOOLYEAR { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
