//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPEACCOUNT
    {
        public TYPEACCOUNT()
        {
            this.ACCOUNT = new HashSet<ACCOUNT>();
        }
    
        public decimal IDTYPE { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<ACCOUNT> ACCOUNT { get; set; }
    }
}
